### ISSUE TITLE
[일일보고] 개발 2랩 정재경 7월 5일

### ISSUE THREAD

**Issue by jjk376** [works-mobile/zip-viewer#2]
# 오늘 할 일
- 자바 스크립트 개론 함수형 프로그래밍, 객체 지향 프로그래밍 정리.
 a. javaScript apply / call
- webpack, react / angular(비교) 조사.
- 전체 화면 개략적으로 그려보기

# 오늘 한 일
- javaScript 코드 어시스턴스 설치(개발환경 설정)
- Spring MVC 프레임워크 설치 (개발 환경 설정)
![default](https://user-images.githubusercontent.com/29144085/27890860-8c3836b6-6230-11e7-91bc-439de2cf3b5e.PNG)
- 자바 스크립트 개론 함수형 프로그래밍 정리.
   a. apply
    `function.prototype.apply()` 메소드는 주어진 `this`값과 `arguments`로 함수를 호출하며, `apply`는 인수 배열 하나를 받는다. 호출은 `fun.apply(thisArg, [argsArray])` 와 같이 한다.

    b. call
    `function.prototype.call()` 메소드는 주어진` this`값 및 **각자에게 제공된 인수**를 갖는 함수를 호출한다. 사용은 `fun.call(thisArg[, arg1[, arg2[]]])` 와 같이 호출한다.

   * thisArg 는 호출될 함수에게 지정될 this 값이며, 호출된 함수 내에서 this가 전달된 thisArg인자와 다를 수 있으며,  null이나 undefined 전역객체로 대체된다.

- webpack 조사.
  * 서버에서 처리하는 로직을 JS로 구현하는 부분이 많아지면서 웹 서비스 개발에서 JS로 작성하는 코드의 양이 늘어났다. 코드의 양이 많아지면서 코드의 유지와 보수가 쉽도록 코드를 모듈로 나누어 관리하는 시스템이 필요해 졌으며, 이를 해결 하기 위해 나온 것이 webpack이다.
  *  이전 부터 JS에 모듈화 시스템을 적용하려는 많은 노력은 있었고, JS 모듈화 명세럴 만드는 대표적 작업 그룹에 CommonJS와 AMD가 있다.
  * webpack은 모듈 시스템을 구성하는 기능 외에도 로더 사용, 빠른 컴파일 속도등의 장점이 있다.
  * webpack은 node.js가 설치된 환경에서 실행된다.

cf) commonJS : 자바 스크립트 어플리케이션에서 어떻게 스크립트 간의 의존성을 선언할 것인지에 대한 일종의 스펙(형식)이다. 아래와 같이 모듈을 선언할 수 있다.

```javascript
var lib require("package/lib");
function foo() {
    lib.log("helloWorld!");
}
exports.foobar = foo;
```
그리고 선언된 모듈들을 처음으로 로드 하는 것은 아래와 같이 require 한다.
```javascript
require(["package/myMoule"],function(myModule{
    myModule.foobar();
});
```
    
  - react / angular 비교 조사
 
_| react |angular
------------ | ------------- | -------------
목적|빠르게 업데이트 하고 렌더링 하는 템플릿을 만드는 JavaScript 라이브러리.| 프론트엔드 코드가 어떤 모습이 되어야 하는 지에 대한 올바른 길을 제시하는 프레임 워크.
장점|복잡하고 큰 유저 인터페이스에서도 훌륭한 성능을 낸다. | 개발 프로세스나 코드의 아키텍처에 대한 수준 향상에 적합. 어플리케이션을 구성하는 JavaScript나 렌더링 될 HTML과 물리적으로 분리하는 방식을 유지.
템플릿|템플릿 오브젝트를 JSX(자바 스크립트의 새로운 확장된 문법. ) 최상단에 올려두고 템플릿을 인라인으로 구성하거나 한 곳에 모든 템플릿을 구성.|

- 화면과 함께 요구 사항 그려보기.
  *  러프 스케치를 그렸으나 너무 지저분 해서 굳이 파일 첨부를 하진 않았습니다.
  다음날 피드백 시간에 좀 알아 볼 수 있게 해서 보여드리겠습니다.

# 내일 할 일
- 러프 스케치 알아 볼 수 있게 그리기
- git hub 사용해보기.
- 피드백 받기.
- webpack 환경설정하기.(node.js 설치)

# 가까운 미래에 할 일
- 필요한 기능 세분화 하여 모듈 형태로 생각해보기.
- sequence diagram 그리기.
- repository 나오면 git hub front end 브랜치 만들기
- 앞으로 github에 올려야 할 사항.
a. Issues : User측면의 기능에서 수행해야할 모듈(issue)을 세밀하게 나눠서 올릴 것.
b. Project : 프로토 타입 제작 해서 test repository에 올릴 것.
c. mileStone : 계획 올릴 것.
d. WIKI : 새롭게 알은 사실들 올릴 것.

# 느낀점
나는 진짜 그림도 못그리고 프레임워크도 못다루고 용어도 못외우는 구나.

**Comment by LJuwon** [comment]
webpack 은 사실 모듈를 관리하는 것은 아니고 번들러의 기능을 수행하는 라이브러리 입니다.
리서치한 내용 중 AMD, CommonJS 가 모듈화 하기 위한 명세이고 webpack 은 AMD, CommonJS 를 지원하는 정도입니다.
git 을 사용하여 코드를 관리하기 때문에 익숙해질 수 있도록 노력해 주시고,
추가로 gitflow 에 대해서도 알아보시기 바랍니다.
